src/Entity/Entity.php
<?php

namespace App\Entity;

use App\Repository\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

#[ORM\Entity(repositoryClass: EntityRepository::class)]
class Entity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: "entity", targetEntity: Image::class, cascade: ["persist"], orphanRemoval: true)]
    private Collection $images;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $pdf_file = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setEntity($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getEntity() === $this) {
                $image->setEntity(null);
            }
        }

        return $this;
    }

    public function getPdfFile(): ?string
    {
        return $this->pdf_file;
    }

    public function setPdfFile(?string $pdf_file): static
    {
        $this->pdf_file = $pdf_file;

        return $this;
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'images')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entity $entity = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEntity(): ?Entity
    {
        return $this->entity;
    }

    public function setEntity(?Entity $entity): static
    {
        $this->entity = $entity;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }
}

src/Controller/EntityController.php
<?php

namespace App\Controller;

use App\Entity\Entity;
use App\Entity\Image;
use App\Form\EntityFormType;
use App\Message\NewEntityPdf;
use App\Repository\EntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class EntityController extends AbstractController
{
    public function __construct(
        private EntityRepository $entityRepository,
        private EntityManagerInterface $entityManager
    ) {
    }

    #[Route('/', name: 'entities')]
    public function index(): Response
    {
        return $this->render('entity/index.html.twig', [
            'entities' => $this->entityRepository->findAll(),
        ]);
    }

    #[Route('/entity/create', name: 'create_entity')]
    public function create(Request $request, MessageBusInterface $bus): Response
    {
        $entity = new Entity();
        $form = $this->createForm(EntityFormType::class, $entity);

        $form->handleRequest($request);

        // Handle form submit and check if form data is valid
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Entity $newEntity */
            $newEntity = $form->getData();

            // Get uploaded image(s)
            $images = $form->get('images');

            foreach($images as $image)
            {
                // Create unique image filename
                $uploadedImage = $image->get('path')->getData();
                $filename = md5(uniqid()) . '.' . $uploadedImage->guessExtension();

                // Save image to uploads dir
                $uploadedImage->move(
                    $this->getParameter('uploads_directory'), $filename
                );

                /** @var Image $newImage */
                $newImage = $image->getData();

                // Set the filename of the Image
                $newImage->setPath($filename);
                $newEntity->addImage($newImage);
            }

            // Save new entity data to db
            $this->entityManager->persist($newEntity);
            $this->entityManager->flush();

            // Generate PDF asynchronously via message queue
            $bus->dispatch(new NewEntityPdf($newEntity->getId()));

            // After saving, redirect user to the entity list page
            return $this->redirectToRoute('entities');
        }

        return $this->render('entity/create.html.twig', [
            'form' => $form,
        ]);
    }
}

templates/entity/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EntityController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <h1 class="mb-2 font-bold">Add New Entity</h1>
        <hr class="py-3" />

        {{ form_start(form) }}

            {{ form_widget(form.name) }}

            {{ form_widget(form.description) }}

            <a href="#" id="js-image-add" class="text-white bg-blue-500 px-2 border rounded py-1 mt-2 float-right text-sm">+ Add Image</a>

            <h3 class="py-2.5">
                Images
            </h3>
            <hr class="mb-2" />

            <div
                id="js-images-wrapper"
                class="row mb-5"
                data-prototype="{{ form_widget(form.images.vars.prototype)|e('html_attr') }}"
                data-index="{{ form.images|length }}"
            >
                {% for image in form.images %}
                    <div class="col-xs-4 js-images-item">
                        <a href="#" class="js-remove-image pull-right">
                            <span class="fa fa-close"></span> Delete
                        </a>
                        {{ form_widget(image.path) }}
                    </div>
                {% endfor %}
            </div>

            <div class="row py-5 mt-5">
                {{ form_widget(form.save) }}
                <a class="text-white bg-gray-500 px-5 py-2.5 rounded font-medium text-base mr-2" href="{{ path('entities') }}">Cancel</a>
            </div>

        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const wrapper = document.getElementById('js-images-wrapper');
            const deleteBtn = wrapper.querySelector('.js-remove-image');

            if (deleteBtn) {
                deleteBtn.addEventListener('click', function(e) {
                    e.preventDefault();
                    wrapper.closest('.js-images-item')
                        .remove();
                })
            }

            document.getElementById('js-image-add').addEventListener('click', function(e) {
                e.preventDefault();

                const prototype = wrapper.dataset.prototype;
                const index = wrapper.dataset.index;
                const newImage = prototype.replace(/__name__/g, index).replace(/&quot;/, '"');


                wrapper.dataset.index = index + 1;
                wrapper.insertAdjacentHTML( 'beforeend', newImage );
            })
        })
    </script>
{% endblock %}

templates/entity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EntityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <a class="text-white bg-blue-500 px-5 py-1.5 rounded font-medium text-sm float-right" href="{{ path('create_entity') }}">+ Create Entity</a>
    <h1 class="mb-2 font-bold text-4xl">
        Entities
    </h1>
    <hr class="py-3" />

    <table class="table-auto border rounded w-full">
        <thead>
            <tr class="bg-gray-100">
                <th class="font-medium text-left px-3 py-2 text-base">Name</th>
                <th class="font-medium text-left px-3 py-2 text-base">Description</th>
                <th class="font-medium text-left px-3 py-2 text-base">Images</th>
                <th class="font-medium text-left px-3 py-2 text-base text-center">Action</th>
            </tr>
        </thead>
        <tbody>
        {% if entities|length > 0 %}
            {% for entity in entities %}
                <tr class="border px-2 py-2">
                    <td class="px-2 py-2 font-normal text-sm">{{ entity.name }}</td>
                    <td class="px-2 py-2 font-normal text-sm">{{ entity.description }}</td>
                    <td class="px-2 py-2 font-normal text-sm" style="max-width: 250px;">
                        {% for image in entity.images %}
                            <img src="{{ asset('uploads/images/' ~ image.path) }}" class="border rounded mr-2 inline-block" style="max-height: 50px;" width="50" height="50" alt="{{ image.path }}" />
                        {% endfor %}
                    </td>
                    <td class="px-2 py-2 font-normal text-sm text-center" style="width: 180px;">
                        <a class="text-white bg-blue-500 px-5 py-1.5 rounded font-medium text-sm" href="{{ asset('downloads/pdfs/' ~ entity.pdfFile) }}" target="_blank">Download PDF</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr class="border px-2 py-2" colspan="4">
                <td class="px-2 py-2 font-normal text-sm">No record(s) yet.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}